swagger: '2.0'
info:
  contact:
    email: jyip@curiouslearning.org
  description: >-
    API to query for application referrals from learning referral network.
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  termsOfService: 'http://curiouslearning.org'
  title: Referral API
  version: 1.0.0
# Hostname of the ESP gateway
host: referral-gateway-hj2cd4bxba-de.a.run.app
basePath: /api/v1
x-google-backend:
  # URL of the API backend
  address: https://learning-referral-network.appspot.com/
  # IAP OAuth Client
  jwt_audience: 972445763316-p4opm7kh8mlhkslu4b7itpjesdqoba5l.apps.googleusercontent.com
schemes:
  - https
paths:
  /referral:
    post:
      tags:
        - query
      operationId: make_recommendation
      summary: 'Request for app referrals from the recommendation engine given a set of user metrics'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: referralRequest  # This is ignored for request body and for documentation only
          description: 'A JSON object containing the parameters for getting referrals from
            the recommendation engine'
          required: true
          schema:
            type: object
            required:
              - package_name
              - locale
            properties:
              package_name:
                type: string
                description: 'Package name of the application making this request. This field is
                  used to provide additional context to the recommendation engine such as locale.
                  For Android applications this would be the com.* package ID.'
              locale:
                type: string
              total_sessions:
                type: integer
                minimum: 0
              average_session_length:
                type: integer
                minimum: 0
              days_since_last_session:
                type: integer
                minimum: 0
              progress_by_skill:
                type: object
                additionalProperties:
                  type: integer
              max_results:
                type: integer
                default: 20
                maximum: 100
                minimum: 1
      responses:
        '200':
          description: 'List of app referrals from the recommendation engine'
          schema:
            $ref: '#/definitions/ReferralResult'
        '400':
          $ref: '#/responses/Invalid'
      x-swagger-router-controller: "controllers.referral"
definitions:
  ApiError:
    properties:
      code:
        format: int32
        type: integer
      message:
        type: string
    required:
      - code
      - message
    type: object
  Application:
    properties:
      description:
        description: >-
          Additional description of the application on the referral UI if we
          don’t want our users to be redirected out of the application to see
          this information
        type: string
      locale:
        description: ISO 639 Locale Code (ie. “en-us”)
        type: string
      platform_id:
        description: >-
          Platform specific unique identifier for the application. This would be
          package name for Android, bundle ID for iOS and URL for web-based
          applications.
        type: string
      title:
        description: Title of the application to be displayed on the referral UI
        type: string
      icon_url:
        description: URL path of the application icon image
        type: string
      skills:
        type: array
        items:
          type: string
        description: >-
          Skills are key-value pairs that describe the application content
          and intent. Certain attributes can be applied to most applications and
          those are defined here. Such attributes are expected to grow as we
          gain more understanding of the product, but existing definitions
          should not change for backward compatibility reasons. Applications are
          not required to have all the attributes defined either. It is also
          possible for applications to provide additional keyword “tags” to help
          improve query relevance.
    type: object
  ReferralItem:
    description: 'Summary and relevance of a referral'
    properties:
      item:
        $ref: '#/definitions/Application'
      score:
        format: float
        type: number
    type: object
  ReferralResult:
    type: object
    description: 'App referrals generated from recommender'
    properties:
      result:
        type: array
        items:
          $ref: '#/definitions/ReferralItem'
securityDefinitions:
  ApiKey:
    type: apiKey
    name: key
    in: query
    description: basic authentication with API key
    x-apikeyInfoFunc: "controllers.auth.verify_apikey"
security:
  - ApiKey: []
tags:
  - description: API to query for recommendations
    name: query
responses:
  Invalid:
    description: Invalid request body
    schema:
      $ref: '#/definitions/ApiError'
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: '#/definitions/ApiError'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/ApiError'

