swagger: '2.0'
info:
  contact:
    email: jyip@curiouslearning.org
  description: >-
    API to query for application referrals from learning referral network.
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  termsOfService: 'http://curiouslearning.org'
  title: Referral API
  version: 1.0.0
# Hostname of the ESP gateway
host: referral-gateway-hj2cd4bxba-de.a.run.app
basePath: /api/v1
x-google-backend:
  # URL of the API backend
  address: https://learning-referral-network.appspot.com/
  # IAP OAuth Client
  jwt_audience: 972445763316-p4opm7kh8mlhkslu4b7itpjesdqoba5l.apps.googleusercontent.com
schemes:
  - https
paths:
  /query:
    get:
      tags:
        - query
      operationId: execute_query
      summary: Query the database
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: limit
          description: 'Maximum number of items to return'
          type: integer
          format: int32
          default: 20
          maximum: 100
          minimum: 1
          required: false
        - in: query
          name: locale
          description: 'Filter results by app locale'
          type: string
          required: true
        - in: query
          name: skills
          description: 'Comma separated list of skills to match, if no skills are supplied, all apps with the
            specified locale will be returned. An app in the result would contain one or more skills listed,
            the matching score reflects the percentage of skill terms matched'
          type: string
          required: false
      responses:
        '200':
          description: Query result
          schema:
            $ref: '#/definitions/QueryResult'
        '400':
          $ref: '#/responses/Invalid'
      x-swagger-router-controller: "controllers.query"
definitions:
  ApiError:
    properties:
      code:
        format: int32
        type: integer
      message:
        type: string
    required:
      - code
      - message
    type: object
  Application:
    properties:
      skills:
        type: array
        items:
          type: string
        description: >-
          Skills are key-value pairs that describe the application content
          and intent. Certain attributes can be applied to most applications and
          those are defined here. Such attributes are expected to grow as we
          gain more understanding of the product, but existing definitions
          should not change for backward compatibility reasons. Applications are
          not required to have all the attributes defined either. It is also
          possible for applications to provide additional keyword “tags” to help
          improve query relevance.
      info:
        $ref: '#/definitions/AppInfo'
    type: object
  MatchingItem:
    description: Matching item from a query
    properties:
      item:
        $ref: '#/definitions/AppInfo'
      score:
        format: float
        type: number
    type: object
  QueryResult:
    description: Result from a application query
    type: object
    properties:
      result:
        type: array
        items:
          $ref: '#/definitions/MatchingItem'
  AppInfo:
    properties:
      description:
        description: >-
          Additional description of the application on the referral UI if we
          don’t want our users to be redirected out of the application to see
          this information
        type: string
      id:
        description: Unique application ID within the database
        format: int64
        type: integer
      locale:
        description: ISO 639 Locale Code (ie. “en-us”)
        type: string
      platform_id:
        description: >-
          Platform specific unique identifier for the application. This would be
          package name for Android, bundle ID for iOS and URL for web-based
          applications.
        type: string
      title:
        description: Title of the application to be displayed on the referral UI
        type: string
    required:
      - id
      - platform_id
      - title
    type: object
securityDefinitions:
  ApiKey:
    type: apiKey
    name: key
    in: query
    description: basic authentication with API key
    x-apikeyInfoFunc: "controllers.auth.verify_apikey"
security:
  - ApiKey: []
tags:
  - description: API for referral query
    name: query
responses:
  Invalid:
    description: Invalid request body
    schema:
      $ref: '#/definitions/ApiError'
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: '#/definitions/ApiError'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/ApiError'


